version: "3.8"
services:
  frontend:
    build: ./nginx
    volumes:
      - './frontend:/app'
    ports:
      - '3100:80'
    depends_on:
      - backend
  backend:
    build: ./php-fpm
    volumes:
      - './backend:/app'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: db
      DATABASE_NAME: infusemedia
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: infusemedia
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3300:3306'
volumes:
  db-data:
  rm-data: